### ISSUE TITLE
Video/Audio Channel

### ISSUE THREAD

**Issue by GeorgeS2019** [SakulFlee/Godot-WebRTC-Match-Maker#81]
sipsocery support video WebRTC

**Comment by SakulFlee** [comment]
Video/Audio channels have not yet been implemented into the plugin, but should be an easy addition.
Should happen after #13.

**Comment by GeorgeS2019** [comment]
great issue 13 closed : https://github.com/SakulFlee/Godot-WebRTC-Match-Maker/issues/13
